### ISSUE TITLE
crobat is not taking input via external defined variables 

### ISSUE THREAD

**Issue by ertanuj96** [Cgboal/SonarSearch#12]
`domain="redbull.com"`
`crobat -s $domain`
no results

while 
`crobat -s redbull.com`
got results 

why this is happening ??? Please help

**Comment by Cgboal** [comment]
Not sure, works for me.

``` normal

λ cgboal [~] → domain=redbull.com

λ cgboal [~] → crobat -s $domain
111megawatt.redbull.com
360content.redbull.com
400.redbull.com
518.redbull.com
account.redbull.com
addons-konzertspektakel.redbull.com
addons.redbull.com
ae-vpn01.redbull.com
afterparty.redbull.com
agtt.redtech.redbull.com
airrace.redbull.com
albumartiq.redbull.com
alas.redbull.com
alexa-vsk-dev.redbull.com
allsnow.redbull.com
amaphiko.redbull.com
amp.redbull.com
amplify.redbull.com
api-d.redbull.com
api-q.redbull.com
api.developers.redbull.com
```

**Comment by ertanuj96** [comment]
Is there some kind of api request limitation in place , as it don't gives result for one domains if we hit the same domains 5-6 times, can you check your api logs .. you will see , I am just hitting your domain search api , but I am getting results in a very few as I am trying to put crobat in my recon workflow , but its not giving any result when it is calling inside some function and pass domain as an argument ?

**Comment by Cgboal** [comment]
No API request limitation in place. Not sure why your script wouldn't be working. Running it in a for loop doesn't get any failed requests. I've done load testing before as well and it should be fine, can handle around 1k requests per second with a total upload from the server of 500Mbits of data per second. 

Can't help debug your script without seeing it.

**Comment by ertanuj96** [comment]
See bro, In this image also, for one website it is giving results as this is fresh one , I didn't hit this before with crobat while second website is old one, I have hit this website before..  In case crobat is showing results , while in second case its not...
![16018910010751235351369](https://user-images.githubusercontent.com/27552153/95064481-6a12e000-071d-11eb-8f19-e6d9cf07b1db.jpg)

**Comment by ertanuj96** [comment]
Bro, Upper Image is normal example of problem without passing it to any script . 
and script part  is here in which crobat is used .
`
domain=
usage() { echo -e "Usage: ./sd_enum_recon.sh -d domain " 1>&2; exit 1; }

while getopts ":d:" o; do
    case "${o}" in
        d)  
            domain=${OPTARG}
            ;;
        *)  
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if [ -z "${domain}" ] ; then
   usage; exit 1;
fi

main(){
echo "Running Sonar DNS subdomain enumeration"
crobat -s $1 | tee sonar
}

main $domain
`

This script part works fine if I hit a new domain that was not hit before , but when I hit older domain that is used before , there is no result as in the Image.

**Comment by ertanuj96** [comment]
And problem is so bigger as this doesn't happen with every domain , this happens randomly 
![16018917360181892651699](https://user-images.githubusercontent.com/27552153/95065735-12757400-071f-11eb-8635-9a85af3bae5b.jpg)

**Comment by Cgboal** [comment]
No idea to be honest. Should always return data, does for me. Very weird. Will look into this later when I have time, at work atm. Does the same happen on your local machine when not SSH'd into an ec2 instance?

**Comment by ertanuj96** [comment]
As far as I am able to test on local machine , its run fines .. no such issue neither directly nor in recon script. I am also stuck on this since last 3 hours , unable to find out why this happening on ec2 instance.. as this only happens with tool , In my recon workflow there are other tools though, those are working fine.. Please look into it, when you gets time, as this project is really helpful in recon, I wouldn't want to hold all sonar data in my vps and grep my target into it, your tool work too great .. speed is blazing fast as you mentioned 🙏.

**Comment by Cgboal** [comment]
Interesting, that is super weird that it doesn't work properly on aws. Will test it out and look into it. Could be the Go version in the amazon AMI.

**Comment by ertanuj96** [comment]
Actually not working properly on local system too , same issue that was on ec2 .. works well when target is new, but when target is old don't work.. 
Might be this issue can be due to network error, you should check api's log and check for what api is returning on particular domains .. you will get be able to verify this issue , either mongo db search query is breaking or there is some network issue problem.

**Comment by ertanuj96** [comment]
Hi Brother, I found a workaround around this problem I don't know why this problem happens but the solution to this problem is just add '.' before the domain name , if its not showing any results crobat will show results then .. I wrote a script for this.. that now its working fine ... Here is the bash script. 
![16020095010341592240526](https://user-images.githubusercontent.com/27552153/95246142-b8b19e80-0831-11eb-99b9-dfaeb2d52953.jpg)
