### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Be1nna** [Cgboal/SonarSearch#13]
Thanks a lot for this tool. But it is very difficult to save the subdomains it finds. Can you bring the feature to save subdomains to file?

**Comment by Cgboal** [comment]
Have you tried redirecting output to a file?

crobat -s omnisint.io > subdomains.txt

**Comment by Be1nna** [comment]
Thank you very much!

**Comment by Cgboal** [comment]
No problem. You can do this with any command
