### ISSUE TITLE
SonarSearch on Debian

### ISSUE THREAD

**Issue by samb00ka** [Cgboal/SonarSearch#18]
Trying to get it working on Debian, but with no success. Could you please give some detailed instructions? Are there any other ways on how to get access to your API?

**Comment by Cgboal** [comment]
What issues are you having?

**Comment by samb00ka** [comment]
I've installed go and then according to the instructions. There were no mistakes during installation, but when I type "crobat -h" I get "bash: go: command not found"

**Comment by Cgboal** [comment]
Is your GOPATH setup correctly?

**Comment by samb00ka** [comment]
Yes, I believe, according to the instructions https://golang.org/doc/install
export PATH=$PATH:/usr/local/go/bin

**Comment by Cgboal** [comment]
Hm, not sure. Try the docker version if you like: 
```
docker run cgboal/crobat -s google.com
```
