### ISSUE TITLE
Bad Gateway: HTTP status code 502

### ISSUE THREAD

**Issue by neilunderwood** [Cgboal/SonarSearch#20]
I just tried firing off an rDNS query with crobat like I do every single day at work, but today all of my queries are returning this error:
`2021/01/04 14:53:25 rpc error: code = Unavailable desc = Bad Gateway: HTTP status code 502; transport: received the unexpected content-type "text/html"`
I tried pulling the latest version but it's all up-to-date.  Not sure what's changed.

**EDIT** - spelling

**Comment by Cgboal** [comment]
Will look into this in the morning

**Comment by neilunderwood** [comment]
Looks like it's all back up today.  Thanks!
