### ISSUE TITLE
server down

### ISSUE THREAD

**Issue by mahmoudtmha** [Cgboal/SonarSearch#22]
{"Message": "server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: localhost:27017, Type: Unknown, Average RTT: 0, Last error: connection() error occured during connection handshake: dial tcp 127.0.0.1:27017: connect: connection refused }, ] }"}

every time i go to reverse any ip it give me this 
so please fix it :)

**Comment by mahmoudtmha** [comment]
@Cgboal if u can help me with fix it

**Comment by mohammed-sec2010** [comment]
2021/02/16 12:08:32 rpc error: code = Unknown desc = server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: localhost:27017, Type: Unknown, Average RTT: 0, Last error: connection() error occured during connection handshake: dial tcp 127.0.0.1:27017: connect: connection refused }, ] }

**Comment by Cgboal** [comment]
Think the db crashed, will fix it now.

**Comment by jaikishantulswani** [comment]
@Cgboal Facing same issue as @mohammed-sec2010 in 3 out of 4 queries 
```
2021/03/01 16:38:15 rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded"

```

**Comment by Cgboal** [comment]
Yeah people keep abusing it and dosing it. Got billed $22 for data transfer
last month lol. Will fix it now.
