### ISSUE TITLE
Error occured while running the script

### ISSUE THREAD

**Issue by LogicalHunter** [Cgboal/SonarSearch#33]
Hello, 

When I run this script, I get the following error message. I tested this on different environments but still got the same error:
rpc error: code = Unknown desc = server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: localhost:27017, Type: Unknown, Average RTT: 0, Last error: connection() error occured during connection handshake: dial tcp 127.0.0.1:27017: connect: connection refused }, ] }

**Comment by Cgboal** [comment]
I am aware of this issue, the current implementation is having significant issues handling the number of requests we receive, this, we keep getting instabilities such as this. I'm currently working on a new version which should handle the load no problem, it should be out by the end of tomorrow.
