### ISSUE TITLE
Sonar website down

### ISSUE THREAD

**Issue by L1ghtn1ng** [Cgboal/SonarSearch#36]
Hi,

When going to the following there is a 525 error
![image](https://user-images.githubusercontent.com/3628354/133116081-1cb0a048-87a1-46fc-9624-9e0c9b907f3c.png)

Is it also possible to set the mime type to be json instead of text/html as that is the wrong mime type

**Comment by indianajson** [comment]
@L1ghtn1ng, the site appears to be up now. Plus, the MIME-type is returning `application/json` for me.

**Comment by Cgboal** [comment]
Hmm dunno what happened there, cheers.
