### ISSUE TITLE
invalid IPv4 address

### ISSUE THREAD

**Issue by neilunderwood** [Cgboal/SonarSearch#37]
Since updating to V2, I've been able to get one search run successfully.  Everything since results in this:

`[09:25:13] user@hostname:~$ crobat -r 8.8.8.8
2021/09/16 09:25:21 rpc error: code = Unknown desc = invalid IPv4 address`

This happens no matter the IP address.  I tried deleting the binary and reinstalling but same story.

ENV:  WSL1 Debian instance running on Windows 10 19042.1165

Thanks for all your efforts.

**Comment by Cgboal** [comment]
Ah really? I changed the way it does IP range calculations yesterday
because it was resulting in DoS. Was working over HTTP but I didn't check
the gRPC one as it uses the same function. I'll look into this asap.

**Comment by Cgboal** [comment]
This is now resolved

**Comment by Cgboal** [comment]
Stupid IPv4 parsing library decided that all IP's in a /32 are 256.256.256.256 

https://github.com/Cgboal/SonarSearch/commit/6b047e51094f873fac3c77e8d0950adcde30bf47#diff-fe4ad137f5a000c082912ddfc13a903ff4e1bb4346fdced5d278de22158d495eR87

**Comment by neilunderwood** [comment]
Thank you so much for getting to this so quickly.  Cheers!

**Comment by Cgboal** [comment]
No problem
