### ISSUE TITLE
GRPC Credientials Error on Installation

### ISSUE THREAD

**Issue by jamesbower** [Cgboal/SonarSearch#5]
When installing on Ubuntu 18.04 I get the following error.

`test@test:~/tools/SonarSearch$ go get github.com/cgboal/sonarsearch/crobat`
`# google.golang.org/grpc/credentials`
`../../go/src/google.golang.org/grpc/credentials/tls.go:245:2: undefined: tls.TLS_AES_128_GCM_SHA256`
`../../go/src/google.golang.org/grpc/credentials/tls.go:246:2: undefined: tls.TLS_AES_256_GCM_SHA384`
`../../go/src/google.golang.org/grpc/credentials/tls.go:247:2: undefined: tls.TLS_CHACHA20_POLY1305_SHA256`
I believe it's related to this. 
[https://github.com/grpc/grpc/issues/23702](https://github.com/grpc/grpc/issues/23702)

**Comment by Cgboal** [comment]
That's weird, guess we'll have to wait and see what the response is to that issue
