### ISSUE TITLE
Deduplication - improvement request

### ISSUE THREAD

**Issue by w9w** [Cgboal/SonarSearch#7]
Hi, Calum! Nice tool! The output would look cooler if you added duplicates deleting. I'm using it with sort -u (crobat -s domain.com | sort -u >> file.txt) now but it'd be great if you added deduplication to your tool.

**Comment by Cgboal** [comment]
Will look into this and get back to you. Should be able to do it in the database query. Initially had quite limited compute resources so was very focused on performance. Got some more resources now so should be able to accommodate this. 

It's fine on stuff like epicgames.com but some queries have 10's of millions of results so doing a unique filter is quite expensive.

**Comment by Cgboal** [comment]
If it proves to be an issue I could add a flag to the client which will automatically sort them by unique on the client side as to keep the server load down, but that runs the risk of resource exhaustion on the client side.

**Comment by Cgboal** [comment]
This is done, if you do -u when running the cli client it will auto unique sort your results. This is not a default option as it can eat ram if doing large queries (millions of results).
