### ISSUE TITLE
SonarSearch Down

### ISSUE THREAD

**Issue by secfb** [Cgboal/SonarSearch#8]
Crobat application and https://sonar.omnisint.io site are not working. The following error comes up.

```bash
2020/08/26 11:32:56 rpc error: code = Unavailable desc = Bad Gateway: HTTP status code 502; transport: received the unexpected content-type "text/html"
```

**Comment by Cgboal** [comment]
Up now, apologies for the inconvenience, should be more consistent when we get the prod server back, it sometimes runs out of RAM on my crappy home server and crashes. Need to make it auto-restart

**Comment by Mr-Hex007** [comment]
Crobat application and https://sonar.omnisint.io/ site are not working. The following error comes up.
Error 522 Ray ID: 71a0bc9e6a588859 • 2022-06-12 07:05:13 UTC
Connection timed out

**Comment by Cgboal** [comment]
Apologies for the downtime. It’s up again now.

**Comment by T0xdz** [comment]
https://sonar.omnisint.io/
Connection timed out Error code 522
