### ISSUE TITLE
Server times out after 120 seconds for large responses.

### ISSUE THREAD

**Issue by xEHLE** [Cgboal/SonarSearch#9]
I noticed that the 120 second timeouts have been removed from the client, but the server still seems to timeout after 120 seconds regardless.
For example searching for "amazonaws.com" cuts off pretty much exactly at 120 seconds with 1491770 domains returned.
Would be nice if the server didnt time out for large responses, for example a timeout after 5-10 seconds after no data has been sent vs. the current 120 second timeout no matter what.

**Comment by Cgboal** [comment]
Ah, yeah, had that exact issue before when doing lookups on amazonaws.com as well. I fixed it but not sure if I i pushed that to prod in the end. Will have to check when i'm home. Try again tomorrow and it'll work

**Comment by Cgboal** [comment]
There are now no server time outs when using gRPC, which the command line client uses by default. Timeouts remain for the REST API as not having them would result in DoS.
